language: java
jdk:
- oraclejdk8
notifications:
  slack:
    secure: jGUFC8IhOgEurs4KCtmKihQOok0v8QZXF1AsuBmLAAIZGEqEGJGV4WunOS7icTT0vMAP+EzISq+YNojv7ncsUN50Re3YlbUX/xAcLEHWKkO0moHiEs7IdgOzxACGDAnLqobuZVT7k3LdwDpsoTDGwgbluBU7nGixW1E0xC5qu5m/1qD5Foim85wllVy2Vj97YFIxhS1jfmT8dCx7v1cND6tyjPxyeV7QoxzXDRKJ0RD2FHUR34wI63JNiJpji6B8EyHcYgnnTEcfGUBTTS4MKgbxo5oJ73iorr4PbU/62W7BPlOfshxjUKvt1y42sxZ7pccQZEDTy+uoo+qosGwB8XN+YiZ8NqiW+O53s7U2Vy/1p0/QEhSVMvE+4FXvJNhMsFsRZSM0EFf0nI4fa2uomgAsu7XpTYi+09GQMB6yfZQWYRN7UATCG3L08yli/uQtLfhW3Xo0rOoD3oFsCOZz5WVDZ2zujAtnh/DBYirGT5YzfnsAsrZgaSlSIkFw14T19Rw7WdSl9EsaEz77KYhStvuG+YJ7v+4g1C2945L7a50VpElbNkDU2did6Out4ZUu3dtIVCJ6KwB6uXRRSgOC1lAv6a/xPEyjZDdg2v0ttzRD+BbogViVicqH+0d8+fiC1RwmxJoDeG9NQakOFS/BfDPbOHVBnMVPNl7nOXs0E5E=
